#!/bin/bash

function can_install {
  programs='kid3 chrome 4kdown megasync pomodone firefox heroku simplenote atom corebird gitkraken tizonia ora tusk brave wavebox typora anoise cloudcross'

  if echo $programs | grep -w $1 >/dev/null
  then
    echo "You can install $1"
  else
    echo "There is no such program as $1"
  fi
}

case $1 in
  '--help' | '-h') less .help_message || cat .help_message;;
  '--list' | '-l') less .app_list || cat .app_list;;
  '--find' | '-f') can_install $2;;

  'kid3')       sudo apt-get install kid3;;
  'chrome')     sudo dpkg -i ../apps/google-chrome.deb >/dev/null 2>&1;;
  '4kdown')     sudo dpkg -i ../apps/4k-videodownloader.deb >/dev/null 2>&1;;
  'megasync')   sudo dpkg -i ../apps/megasync.deb >/dev/null 2>&1;;
  'pomodone')   sudo dpkg -i ../apps/pomodone.deb >/dev/null 2>&1;;
  'firefox')    sudo snap install firefox;;
  'heroku')     sudo snap install heroku;;
  'simplenote') sudo snap install simplenote;;
  'atom')       sudo snap install atom;;
  'corebird')   sudo snap install corebird;;
  'gitkraken')  sudo snap install gitkraken;;
  'tizonia')    sudo snap install tizonia;;
  'ora')        sudo snap install ora;;
  'tusk')       sudo snap install tusk;;
  'brave')      sudo snap install brave;;
  'wavebox')    sudo snap install wavebox;;
  'zenkit')     sudo snap install zenkit;;
  'typora')
                wget -qO - https://typora.io/linux/public-key.asc | sudo apt-key add -
                sudo add-apt-repository 'deb https://typora.io/linux ./'
                sudo apt-get update
                sudo apt-get install typora;;
  'anoise')
                sudo add-apt-repository ppa:costales/anoise
                sudo apt-get update
                sudo apt-get install anoise;;
  'cloudcross')
                sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/MasterSoft24/xUbuntu_17.04/ /' > /etc/apt/sources.list.d/cloudcross.list" 
                sudo apt-get update
                sudo apt-get install cloudcross;;
  'windscribe')
                echo "Windscribe. VPN for Linux"
                sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key FDC247B7
                echo 'deb https://repo.windscribe.com/ubuntu zesty main' | sudo tee /etc/apt/sources.list.d/windscribe-repo.list
                sudo apt-get update
                sudo apt-get install windscribe-cli;;
  'anki')       
                echo "Anki"
                tar -xjf ../apps/anki.tar.bz2
                cd anki-2.0.50
                sudo make install >/dev/null 2>&1
                cd ..
                rm -rf anki-2.0.50

                # mplayer (for Anki)
                sudo apt-get install mplayer;;
  'steam')      
                echo "Steam"
                wget -q https://steamcdn-a.akamaihd.net/client/installer/steam.deb
                sudo dpkg -i steam.deb >/dev/null 2>&1;;
  'ggl_player') echo "Google Music Player" && sudo dpkg -i ../apps/google-music-player.deb >/dev/null 2>&1;;
  'ffmpeg')     echo "FFmpeg" && sudo snap install ffmpeg;;
  'mkvtoolnix') echo "mkvtoolnix" && sudo snap install matroska-tools;;
  'fast')       echo "Fast by Netflix" && sudo snap install fast;;
  'deezer')     echo "Deezer" && wget -qO "mellow-player" "https://bintray.com/colinduquesnoy/MellowPlayer/download_file?file_path=stable%2F3.5.0%2FMellowPlayer-x86_64.AppImage";;
esac
