#!/bin/bash

if [[ $1 == "--help" || $1 == "-h" ]]
then
    cat .help_message
    exit 0
fi

case $1 in
    'kid3')       sudo apt-get install kid3;;
    'chrome')     sudo dpkg -i ../apps/google-chrome.deb >progress.txt;;
    '4kdown')     sudo dpkg -i ../apps/4k-videodownloader.deb >progress.txt;;
    'megasync')   sudo dpkg -i ../apps/megasync.deb >progress.txt;;
    'firefox')    sudo snap install firefox;;
    'heroku')     sudo snap install heroku;;
    'simplenote') sudo snap install simplenote;;
    'atom')       sudo snap install atom;;
    'corebird')   sudo snap install corebird;;
    'gitkraken')  sudo snap install gitkraken;;
    'tizonia')    sudo snap install tizonia;;
    'ora')        sudo snap install ora;;
    'tusk')       sudo snap install tusk;;
    'brave')      sudo snap install brave;;
    'wavebox')    sudo snap install wavebox;;
    'zenkit')     sudo snap install zenkit;;
    'typora')
                  sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA300B7755AFCFAE
                  sudo add-apt-repository 'deb https://typora.io/linux ./'
                  sudo apt-get update
                  sudo apt-get install typora;;
    'anoise')
                  sudo add-apt-repository ppa:costales/anoise
                  sudo apt-get update
                  sudo apt-get install anoise;;
    'cloudcross')
                  sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/MasterSoft24/xUbuntu_17.04/ /' > /etc/apt/sources.list.d/cloudcross.list" 
                  sudo apt-get update
                  sudo apt-get install cloudcross;;
esac
