#!/bin/bash

# Grub
echo "Open grub settings? (y/n)"
read action

if [[ $action = 'y' ]]
then
    sudo vim /etc/default/grub || sudo nano /etc/default/grub
    sudo update-grub
fi

clear

# Network connction
echo "Configure internet connection?"
read action

if [[ $action = 'y' ]]
then
    pppoeconf
fi

clear

# Turning off useful services
echo "Disable useless services?"
read action

if [[ $action = 'y' ]]
then
    sudo apt-get install bum
    sudo bum
fi

clear

# Installing apps
echo "Installing apps"
scripts/install_apps
clear

# Configure applications
echo "Configuring applications"
scripts/setting_apps
clear
