#!/bin/bash

# Yandex.Disk
echo "Yandex.Disk"

wget -qO - https://repo.yandex.ru/yandex-disk/YANDEX-DISK-KEY.GPG | sudo apt-key add -
echo "deb https://repo.yandex.ru/yandex-disk/deb/ stable main" | sudo tee /etc/apt/sources.list.d/yandex-disk.list
sudo apt-get update
sudo apt-get install yandex-disk

clear

# Yandex.Browser
echo "Yandex.Browser"

wget -qO - https://repo.yandex.ru/yandex-browser/YANDEX-BROWSER-KEY.GPG | sudo apt-key add -
echo "deb https://repo.yandex.ru/yandex-browser/deb/ beta main" | sudo tee /etc/apt/sources.list.d/yandex-browser.list
sudo apt-get update
sudo apt-get install yandex-browser-beta

clear

# Opera
echo "Opera"

wget -qO- https://deb.opera.com/archive.key | sudo apt-key add -
sudo add-apt-repository 'deb https://deb.opera.com/opera-stable/ stable non-free'
sudo apt-get update
sudo apt-get install opera-stable

clear

# Telegram
echo "Telegram"
sudo snap install telegram-desktop
clear

# Deluge
echo "Deluge"
sudo apt-get install deluge
clear

# Sublime Text 3
echo "Sublime Text 3"

wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
sudo apt-get install apt-transport-https
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt-get update
sudo apt-get install sublime-text

clear

# Mailspring
echo "Mailspring"
sudo snap install mailspring
clear

# VS Code
echo "VS Code"
sudo snap install vscode
clear

# Git
echo "Git"
sudo apt-get install git
clear

# Python Pip
echo "Pip"
sudo apt-get install python3-pip
clear

# Vim
echo "Vim"
sudo apt-get install vim
clear

# Deezer
echo "Deezer"
wget -qO "mellow-player" "https://bintray.com/colinduquesnoy/MellowPlayer/download_file?file_path=stable%2F3.5.0%2FMellowPlayer-x86_64.AppImage"
clear

# Spotify
echo "Spotify"
sudo snap install spotify
clear

# Steam
echo "Steam"
wget -q https://steamcdn-a.akamaihd.net/client/installer/steam.deb
sudo dpkg -i steam.deg >progress.txt
clear

# Anki
echo "Anki"

tar -xjf ../apps/anki-2.0.50-amd64.tar.bz2
cd anki-2.0.50
sudo make install >progress.txt
cd ..
rm -rf anki-2.0.50

# mplayer (for Anki)
sudo apt-get install mplayer

clear

# Okular
echo "Okular"
sudo snap install okular
clear

# VLC
echo "VLC"
sudo snap install vlc
clear

# MEGA Sync
echo "MEGA Sync"
sudo dpkg -i ../apps/megasync-xUbuntu_16.04_amd64.deb >progress.txt
clear

# My Apps
echo "My Apps"

tar -xjf ../apps/my_apps.tar.bz2
mv my_../apps/* $HOME
