#!/bin/bash

# Yandex.Disk
echo "Configuring Yandex.Disk"
yandex-disk setup
clear

# Git
echo "Configuring Git"

read -p "username (leave empty for default): " username
read -p "email (leave empty for default): " email

if [[ -z $username ]]
then
    username='yalexaner'
fi

if [[ -z $email ]]
then
    email='yachmenev.aleksandr2000@gmail.com'
fi

git config --global user.name $username
git config --global user.email $email
git config --global core.editor vim
