#!/bin/bash

# LastPass
echo "Configuring LastPass"

read -p "username: " username
lpass login $username
clear

# Yandex.Disk
echo "Configuring Yandex.Disk"
yandex-disk setup
clear

# Windscribe
echo "Configuring Windscribe"
windscribe login

read -p "Connect now? [y/n]: " action

if [[ $action = 'y' ]]
then
    windscribe connect
fi

clear

# Git
echo "Configuring Git"

read -p "username (leave empty for default): " username
read -p "email (leave empty for default): " email

if [[ -z $username ]]
then
    username='yalexaner'
fi

if [[ -z $email ]]
then
    email='yachmenev.aleksandr2000@gmail.com'
fi

git config --global user.name $username
git config --global user.email $email
git config --global core.editor vim

clear